### ISSUE TITLE
XPSNR Tune

### ISSUE THREAD

**Issue by gianni-rosato** [gianni-rosato/svt-av1-psy#1]
SvtAv1EncApp already has PSNR & SSIM RDO tunes, so I think an XPSNR tune would go a very long way. I am definitely in over my head with this one though, so let me know if you can help, or just make a PR!

**Comment by gianni-rosato** [comment]
https://github.com/gianni-rosato/xpsnr

**Comment by fabiorug** [comment]
https://github.com/gianni-rosato/xpsnr/commit/d86c164b5f8a685830ee52896b490c903c9e8d6c#diff-6b79ce28905155e61de292b88cd21d48015e3fbbc3bbe97cf1669cf2fb9211f1
this file is bugged.

**Comment by fabiorug** [comment]
> https://github.com/gianni-rosato/xpsnr/commit/d86c164b5f8a685830ee52896b490c903c9e8d6c#diff-6b79ce28905155e61de292b88cd21d48015e3fbbc3bbe97cf1669cf2fb9211f1
> this file is bugged.

Now is fixed.

**Comment by shssoichiro** [comment]
It's important to note that the PSNR and SSIM tunes don't measure PSNR or SSIM, they're simply optimized to maximize the relevant metric. In essence, svt-av1-psy so far has become a "ssimulacra2" pseudo-tuned, in that we've been using that as the primary metric to measure against.

**Comment by gianni-rosato** [comment]
I don't think we're interested in pursuing this further, so I think it is a safe bet to say this should be closed.
