### ISSUE TITLE
[ENHANCEMENT] Optimize 32 and wider avx2 block subtract

### ISSUE THREAD

**Issue by gitoss** [gianni-rosato/svt-av1-psy#104]
**Is your feature request related to a problem? Please describe.**
I was sad to tee this avx speedup being revereted - it never crashed for me: https://github.com/gianni-rosato/svt-av1-psy/commit/577a91476b31156e2afa1726f6a832bf4c5a926f

**Describe the solution you'd like**
I'd like the fastest svt-av1 :-) and I hope someone figures out what the cause of the reported crashes were - if it only was an optimization flag that probably can be solved by enforcing a compatible optimizaion?

**Describe alternatives you've considered**
I've patched my local git directory to add the faster subtract32_avx2, and was considering adding it to my own git fork - but it's all a hassle, plus it doesn't help other users

**Additional context**

**Comment by gianni-rosato** [comment]
We've thoroughly investigated the issue, and we're able to reproduce crashes. We are not retaining this feature, and we do not currently have a solution - we are also not currently looking for one.
