### ISSUE TITLE
[ENHANCEMENT] tune psy --tune 4 with featues from aom -tune=ssimulacra2 and svt --avif

### ISSUE THREAD

**Issue by gitoss** [gianni-rosato/svt-av1-psy#105]
**Is your feature request related to a problem? Please describe.**
I'm using avif more often lately becasue jxl adoption for web and devices seems to hampred by Google.

The psy --tune 4 is great, but the new kid on the block is aom -tune=ssimulacra2 - here's a thread and even a comparison (though biased towards aom, because thee measurement score is exactly what aom is tuned for):

https://github.com/AOMediaCodec/libavif/issues/2412#issuecomment-2518610778
https://github.com/webmproject/codec-compare/issues/17

**Describe the solution you'd like**
If you -psy devs didn't already do it, looking at whatever aom is doing with its image tuning might be worth considering for svt, too. https://aomedia.googlesource.com/aom/+log/refs/heads/main

And of course you've already seen the memory-reducing --avif mode of mainline: https://gitlab.com/AOMediaCodec/SVT-AV1/-/commit/7faf0462f32ba9ad61f17b5f30e0939e1f0723a4

**Describe alternatives you've considered**
I've considered switching to aom, but am not yet convinced aom is and will keep being superior to svt for image encoding.

**Additional context**
I'm aware that svt cannot do 444, but imho 420 is just fine for most lossy image encoding.

**Comment by juliobbv-p** [comment]
So, libaom's tune=ssimulacra2's tweaks (Variance Boost, chroma delta q offset and QM, rdmult scaling, etc) actually come from SVT-AV1-PSY's tune=4, with some extra tweaks for 4:4:4. So feel free to give libaom's new tune a try.

Tune "ssimulacra2" is actually kind of a misnomer -- it performs as well (or even better) with other modern image metrics like DSSIM and Butteraugli (for distances <2.5).

That said, libaom doesn't allow to thread encodes as well as SVT-AV1-PSY, so you might need to factor in the need to parallel encode images to get adequate CPU core saturation.
