### ISSUE TITLE
[BUG] Can't disable noise-norm-strength with tune 3

### ISSUE THREAD

**Issue by Uranite** [gianni-rosato/svt-av1-psy#108]
**Overview**
noise-norm-strength can't be disabled with tune 3, because when noise-norm-strength is set to 0, it will be set to 3.
https://github.com/gianni-rosato/svt-av1-psy/blob/916cabd50bbaba3728def160f0b8aa9cb418aa5c/Source/Lib/Codec/full_loop.c#L1487-L1490

**Branch**
In which branch does the issue appear to be occurring?
- [x] `master`
- [x] `testing`

**Reproduction**
To see that indeed noise-norm-strength 0 and noise-norm-strength 3 results in the same video with tune 3, we can do a test encode
Test video: https://media.xiph.org/video/derf/y4m/tt_sif.y4m
1. Encode a video with tune 3 and noise-norm-strength 0
```pwsh
av1an -i tt_sif.y4m -e svt-av1 -v "--tune 3 --noise-norm-strength 0" -o tt_sif_norm0.mkv
```
2. Encode a video with tune 3 and noise-norm-strength 3
```pwsh
av1an -i tt_sif.y4m -e svt-av1 -v "--tune 3 --noise-norm-strength 3" -o tt_sif_norm3.mkv
```
3. Compare the video and see that they're indeed the same video, checking the source code, we see that noise-norm-strength cant be disabled with tune 3 because noise-norm-strength 0=3.

**Expected behavior**
We should be able to disable noise-norm-strength with tune 3 by setting noise-norm-strength to 0.

**Terminal Output**
If applicable, add terminal output to help explain your problem.

**Platform (please complete the following information):**
 - Windows 11
 - Clang-CL 19.1.5
 - Build Command (`./build.sh [args]` that you used to build the problematic binary)

**Version String (please complete the following information):**
- Run `SvtAv1EncApp --version` and copy the result: `SVT-AV1-PSY v2.3.0 (release)
PSY Release: N/A`

**Additional context / Relevant Files**
This issue was brought to me by Itachi Uchiha in the AV1 weeb edition discord.

**Comment by gianni-rosato** [comment]
This is intentional, and not a bug. If you wish for this to change, please open a feature request or a discussion post and we can consider the upsides and downsides of this change.
