### ISSUE TITLE
[DOCS] Mention that --noise-norm-strength 3 is the default for --tune 3

### ISSUE THREAD

**Issue by gitoss** [gianni-rosato/svt-av1-psy#119]
**Overview**
The docs (help file and --help) state that --noise -norm-strength 0 is the default, but it defaults to 3 on --tune 3.

**Branch**
In which branch does the issue appear to be occurring?
- [x] `master`
- [x] `testing`

**Reproduction**
1. enccode a video with --tune 3 and don't set --noise-norm strength
2. observe terminal output
3. compare with svtav1encapp.exe --help & https://github.com/gianni-rosato/svt-av1-psy/blob/master/Docs/Parameters.md

**Expected behavior**
The docs state what the app does.

**Terminal Output**
... encode: Svt[info]: SVT [config]: Temporal Filtering Strength / Noise Normalization Strength     : auto / 3
... --help: --noise-norm-strength        [PSY] Noise normalization strength, default is 0 [0-4]

**Platform (please complete the following information):**
 - Windows 11 [Version 10.0.22631.4602]
 - Clang 19.1.6
 - build.bat [default settings]

**Version String (please complete the following information):**
SVT-AV1-PSY v2.3.0-A (release)
PSY Release: A

**Additional context / Relevant Files**
https://github.com/gianni-rosato/svt-av1-psy/issues/108#issuecomment-2564700031

**Comment by silverbacknet** [comment]
The tunes each adjust a fair number of parameters; the fact that noise-norm-strength couldn't be overridden to 0 is a bug, but not the missing specifics of what every tune does. Plus if you look at the main readme, it's already there:

> --noise-norm-strength 0 to 4
> In a scenario where a video frame contains areas with fine textures or flat regions, noise normalization helps maintain visual quality by boosting certain AC coefficients. The default value is 0, but it is enabled at strength 3 when using Tune 3.
