### ISSUE TITLE
[ENHANCEMENT] GUI/How-to

### ISSUE THREAD

**Issue by LTGM** [gianni-rosato/svt-av1-psy#15]
It would be nice to have GUI or a how-to for some slightly less involved in the scene people to avoid spending lots of time figuring things out. Otherwise, thanks for your involvement! :-)

**Comment by gianni-rosato** [comment]
Hey!

A GUI isn't in the scope of this project specifically, as the goal is to provide an encoder for use either as a standalone binary (where it isn't very useful) or within other projects.

That being said, I maintain a GUI for Linux called Aviator! It is available as a Flatpak, and it uses SVT-AV1-PSY under the hood by default no matter what distro you're on. See more [here](https://github.com/gianni-rosato/aviator) ([Flathub Link](https://flathub.org/apps/net.natesales.Aviator))

If you'd like more flexibility via the command line, check out [rAV1ator CLI](https://wiki.x266.mov/docs/utilities/rav1ator-cli). If you are on Windows, there is a WSL installation tutorial on the wiki page. I pre-compiled binaries with rAV1ator CLI alongside an easy-to-use TUI for installing them, so after the initial setup you do not need to build SVT-AV1-PSY yourself.

Thanks for your interest, I hope one of these two tools works for you!
