### ISSUE TITLE
[ENHANCEMENT] Add "Encode Settings" and "Writing library" to video bitstream just like x264 and x265 for transparency

### ISSUE THREAD

**Issue by vincejv** [gianni-rosato/svt-av1-psy#40]
**Is your feature request related to a problem? Please describe.**
to show what encode settings were used in encoding the video

**Describe the solution you'd like**
implement a solution like x264 and x265 encoders does

**Describe alternatives you've considered**
manually maneuver thru mkvtoolnix and add tags to the video, but it's in the mkv container and not the video bitstream itself or specify during the upload what parameters you used

**Additional context**
n/a

**Comment by vincejv** [comment]
more of an upstream issue

**Comment by Dendraspis** [comment]
Would it be possible for you guys to re-think this enhancement one more time?

Mainline request:
https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues/1912

Answer from 2 months ago:
> ***"[..] no plans from the core dev team on supporting it so far."***

I don't know why nobody cared about a proper integration when the specs were made, but it is such an important information which can be extremely useful.

**Comment by gianni-rosato** [comment]
I apologize, but I don't think this is going to be a consideration on our end until mainline acknowledges they would like to properly support this.

**Comment by Dendraspis** [comment]
Thanks for the answer, even if it's not what I was hoping to read.  😅 
Such a pity that it was not including from the beginning...
