### ISSUE TITLE
Compiling SVT-AV1-PSY with libdovi as a static version under Windows with msvc not possible

### ISSUE THREAD

**Issue by Patman86** [gianni-rosato/svt-av1-psy#41]
Without libdovi, compiling under Windows with msvc works fine. Since this version of SVT-AV1 is advertised with Dolby Vision support, I tried to compile it with msvc, unfortunately without success.

I compiled libdovi with the Windows version of c-cargo and adjusted some references, since the search for the lib doesn't work in this case. Is there a trick here or is the approach different? Please check this or correct the description of how this should work under Windows.

**Comment by vincejv** [comment]
Off-topic, but have you tried mingw msvc? Mingw also compiles offers faster code afaik...
Also I've been compiling using mingw msvc with dovi support without issues

**Comment by gianni-rosato** [comment]
Build instructions are posted [here](https://github.com/gianni-rosato/svt-av1-psy/blob/testing/Docs/PSY-Development.md#windows), and these docs will make their way to the main branch soon enough. Are you able to confirm that with properly configured `libdovi` using one of our supported build methods, you are unable to get a working `SvtAv1EncApp` binary with Dolby Vision support? If so, can you provide the error that is produced upon a failed build?

**Comment by Patman86** [comment]
The DoVi library causes the problems, has nothing directly to do with SVT-AV1-PSY. DoVi does not seem to be designed to be compiled under Windows. Could that be the case? I'll post the error code later.

**Comment by gianni-rosato** [comment]
I can't say what your issue may be until I see an error. If you believe this is not related to SVT-AV1-PSY, please file an issue on the [dovi_tool respository](https://github.com/quietvoid/dovi_tool) and close this one.

In the meantime, using msys2 with libdovi appears to be functional for building a Windows binary. The process is detailed in the build instructions I linked in my last comment.

**Comment by Patman86** [comment]
I was able to solve the problem, but had to make some adjustments. The _Source/App/EncApp/EbAppConfig.h_ file must be expanded to include the following part.

```
#ifdef _MSC_VER
#pragma comment(lib, "ntdll.lib")
#pragma comment(lib, "userenv.lib")
#pragma comment(lib, "bcrypt.lib")
#pragma comment(lib, "ws2_32.lib")
#endif
```
 I added this part after:

```
#ifdef LIBDOVI_FOUND
#include <libdovi/rpu_parser.h>
#endif
```

**Comment by Uranite** [comment]
I believe this issue should be reopened because by default, it's not possible to build svt-av1-psy with libdovi and libhdr10plus with msvc. And I don't want to use msys2 for svt-av1-psy because it results in slower binaries compared to msvc, and with clang-cl its even faster.

After looking at the CMakeLists.txt file, I found that it's using pkg-config to locate libdovi and libhdr10plus. After I've properly installed libdovi and libhdr10plus, and properly configured pkg-config with the `PKG_CONFIG_PATH` and `PKG_CONFIG_LIBDIR` environment variable, svt-av1-psy still fails to detect libdovi and libhdr10plus. I believe the real issue here is that the code for libdovi and libhdr10plus detection doesn't work on windows.

Here is `pkg-config --list-all` output, just to show that I've installed libdovi and libhdr10plus properly.
```
> pkg-config --list-all
dovi         dovi - Dolby Vision metadata parsing and writing
hdr10plus-rs hdr10plus-rs - HDR10+ metadata parsing and writing
```

**Comment by Patman86** [comment]
As already mentioned in my Git, I will provide you with detailed instructions this weekend. I have adapted the file where the files can be found because this does not work via Windows. In addition, these two libs would have to be generated via Windows! The instructions will follow!

**Comment by gianni-rosato** [comment]
@Patman86 if you would open a PR once you're done, that would be great. You can add documentation to the PSY Development page linked from the README.

**Comment by Patman86** [comment]
I don't know if a PR makes sense, because the directory will then be static and must be in the source folder of SVT-AV1-PSY. In addition, the versions of libdovi and libhdr10plus must have been compiled with GCC or MSVC. I have tried many possibilities and unfortunately the static one was the only one that worked.
