### ISSUE TITLE
Add dolby-vision-rpu to EbSvtAv1EncConfiguration

### ISSUE THREAD

**Issue by levogevo** [gianni-rosato/svt-av1-psy#44]
**Is your feature request related to a problem? Please describe.**
There is not a way to load RPU units into the svt encoder from ffmpeg using svtav1-params.

**Describe the solution you'd like**
add the path parameter to the svtav1-params (`EbSvtAv1EncConfiguration` and `svt_av1_enc_parse_parameter`).

**Describe alternatives you've considered**
- I believe (haven't tried) there is a way to pass stdout from ffmpeg into the EncApp, however I do think a proper param would be nice.
- The best solution would be to try to obtain the RPU units directly from the source file, perhaps checking for existence of dovi metadata, and parsing units if so. This way, the need to accept a path variable (uint8_t*), which I haven't seen any other param be like that in my brief look, is not needed in the first place.

**Additional context**
none.

**Comment by gianni-rosato** [comment]
I'm pretty sure this functionality is addressed by [FFmpeg 7.0](https://git.videolan.org/?p=ffmpeg.git;a=blob_plain;f=Changelog;hb=n7.0), so I don't know if DoVi support outside of the `SvtAv1EncApp` binary is a big concern for us at this point

**Comment by levogevo** [comment]
The 7.0 release did add support but only for dovi profile 10. My example test encode with profile 7 does not get included in the side data in the output. I was hoping that libdovi/dovi_tool would help fill in the gaps, until (if) ffmpeg starts supporting more profiles in the side data.
