### ISSUE TITLE
Var-boost 8x8 algorithm can be prone to temporal pulsing for higher CRFs (>=40) and high boost strengths

### ISSUE THREAD

**Issue by juliobbv-p** [gianni-rosato/svt-av1-psy#5]
Settings: --variance-boost-strength 3 --new-variance-octile 4 --crf 40

Parasite @ 39:22, Blu-Ray source
There's incoming sunlight light coming from the car's back window that's shining through the passenger's face and hair. The hair shows noticeable pulsing (detail disappearing and reappearing), which doesn't happen in the 64x64 version of the encode.

Avenues to explore:
- Find how variance in the affected superblocks varies over time
- Explore making the selected boost from 8x8 variances more robust (averaging between values near octile, temporal smoothing, etc)

**Comment by juliobbv-p** [comment]
Update: further evaluation like pulsing for the problematic scene is essentially eliminated when any of these conditions are true:
- CRF is reduced to 30 and less, *or*
- Boost strength is reduced to 2 and less

Short term, I'll be making a point release that makes strength 2 the default for var-boost. At this stage, it's best to offer something gentle, but reliable. Long term, I'm keeping this open to make higher CRFs on higher strengths behave better.

**Comment by juliobbv-p** [comment]
Changed default strength to "gentle" here: https://github.com/gianni-rosato/svt-av1-psy/commit/6c1740e304abc1805505dd47633d058f6a0b4051.

**Comment by fabiorug** [comment]
Lower by 46 percent
