### ISSUE TITLE
[BUG] Wrong default tune shown in --help output

### ISSUE THREAD

**Issue by Uranite** [gianni-rosato/svt-av1-psy#58]
**Overview**
SvtAv1EncApp --help output shows that default tune is 1 even though the default is 2

**Reproduction**
1. Run SvtAv1EncApp --help
2. Find --tune under AV1 Specific Options
3. Observe that it says the default tune is 1

**Expected behavior**
It should say that the default is 2

**Terminal Output**
![image](https://github.com/gianni-rosato/svt-av1-psy/assets/62639703/3f22dc85-61d8-4993-b9a7-3f9a9e3cdc43)

**Version String (please complete the following information):**
- `SVT-AV1-PSY v2.1.0-A (release)
PSY Release: A`

**Comment by gianni-rosato** [comment]
5b4e74d8a7cab770dd35074807cb90d482bbe2e8
