### ISSUE TITLE
[BUG] Wrong version tag when compiling from github releases source code

### ISSUE THREAD

**Issue by Uranite** [gianni-rosato/svt-av1-psy#60]
**Overview**
When compiling from github releases source code download option, the version is v2.1.0rc2 instead of v2.1.0-A

**Branch**
In which branch does the issue appear to be occurring?
- [ ] `master`
- [ ] `testing`

**Reproduction**
1. Download "Source code (zip)" from https://github.com/gianni-rosato/svt-av1-psy/releases/tag/v2.1.0-A
2. Compile svt-av1-psy as usual, I'm on windows, so I'm using `.\build.bat 2022 release static no-dec` to easily compile svt-av1-psy
3. Run the compiled build, on windows, this would be `.\SvtAv1EncApp.exe`
4. Observe that the version is v2.1.0rc2 instead of v2.1.0-A

**Expected behavior**
The version should be v2.1.0-A instead of v2.1.0rc2

**Terminal Output**
```
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:       SVT-AV1-PSY Encoder Lib v2.1.0rc2
Svt[info]: SVT [build]  :       Visual Studio 2022 64 bit
Svt[info]: LIB Build date: Jun 27 2024 13:04:06
Svt[info]: -------------------------------------------
```

**Platform (please complete the following information):**
 - Windows 11
 - MSVC v143
 - `.\build.bat 2022 release static no-dec`

**Version String (please complete the following information):**
- Run `SvtAv1EncApp --version` and copy the result: `SVT-AV1-PSY v2.1.0rc2 (release)
PSY Release: A`

**Additional context / Relevant Files**
Add any other context about the problem here, or files that must be attached for reproduction of the issue, visual inspection, etc.

**Comment by gianni-rosato** [comment]
a0ee8a2660533e84a7b7d581d3b8b50200ea7ad8
