### ISSUE TITLE
[ENHANCEMENT] speedups from aomenc

### ISSUE THREAD

**Issue by gianni-rosato** [gianni-rosato/svt-av1-psy#62]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
There are some patches from aomenc that would speed up encoding:
> https://aomedia.googlesource.com/aom/+/666ed70d03dbd49984a3d08738472b033d18b0fd
> https://aomedia.googlesource.com/aom/+/ea4e4209f105a90a3da431d4e975510f63dc1af9
via @R1chterScale

**Comment by BlueSwordM** [comment]
The enhancements have been added to the #testing branch for testing.

**Comment by BlueSwordM** [comment]
> > The enhancements have been added to the #testing branch for testing.
> 
> Are these AVX2 enhancements used in AVX512 builds, too (when setting -asm AVX512)? Thanks.

Yes. If an equivalent AVX512 SIMD/vector function isn't present, the AVX2 function will be used  instead.

**Comment by BlueSwordM** [comment]
The proper enhancements have been added in mainline.
