### ISSUE TITLE
[BUG] Y4M pipe broken

### ISSUE THREAD

**Issue by tuanden0** [gianni-rosato/svt-av1-psy#67]
**Overview**
Using y4m pipe cause errno: 32
In the help command, it support y4m
```
-i, --input                      Input raw video (y4m and yuv) file path, use `stdin` or `-` to read from pipe
-b, --output                     Output compressed (ivf) file path, use `stdout` or `-` to write to pipe
```

**Branch**
In which branch does the issue appear to be occurring?
- [x] `master`
- [ ] `testing`

**Reproduction**
1. Run this CLI `vspipe test.vpy - -c y4m | SvtAv1EncApp -i stdin --crf 25 -b output.ivf`
2. See error

**Expected behavior**
Can run without error

**Terminal Output**
```
E:\Download\t>vspipe test.vpy - -c y4m | SvtAv1EncApp -i stdin --crf 25 -b output.ivf
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:       SVT-AV1-PSY Encoder Lib v2.2.1
Svt[info]: SVT [build]  :       Visual Studio 2022 64 bit
Svt[info]: LIB Build date: Aug 29 2024 22:36:17
Svt[info]: -------------------------------------------
Error: fwrite() call failed when writing frame: 0, plane: 0, errno: 32
Output 33 frames in 1.92 seconds (17.21 fps)
```

**Platform (please complete the following information):**
 - Windows 11
 - SVT-AV1-PSY Encoder Lib v2.2.1
 - Visual Studio 2022 64 bit

**Version String (please complete the following information):**
- SVT-AV1-PSY Encoder Lib v2.2.1

**Additional context / Relevant Files**
test.vpy

```
import vapoursynth as vs

core = vs.core
clip = core.lsmas.LWLibavSource("source.mkv")
clip = clip.resize.Spline36(1280, 720)
clip = clip[0:1000]
clip.set_output()
```

**Comment by brick2008** [comment]
same error

**Comment by gianni-rosato** [comment]
Hi, thanks for the issue report!

Can you confirm for us whether this is reproducible using mainline SVT-AV1? Thanks so much.

**Comment by tuanden0** [comment]
@gianni-rosato 

Right now, I am unable to check with standalone mainline SVT-AV1. But I can encode with ffmpeg that enable SVT-AV1 (not sure it because ffmpeg handle the pipe from vapoursynth to avoid this issue).

I use the release bin in your release repo and the issue still exists.

Also I try to use the community build from [here ](https://github.com/gianni-rosato/svt-av1-psy/discussions/66#discussioncomment-10509996) and it works.

**Comment by gianni-rosato** [comment]
So you're saying the community build works but the official build doesn't?

**Comment by tuanden0** [comment]
@gianni-rosato 

Yes, I can confirm the community build works but the official build doesn't

**Comment by gianni-rosato** [comment]
Gotcha, thanks for the additional information. We're going to be taking the official build down shortly, and in the future, official Windows builds will not be provided.

**Comment by tuanden0** [comment]
@gianni-rosato 

Sad, I hope you guys still support official build for windows.
