### ISSUE TITLE
[ENHANCEMENT] Add LLVM & version with VC to "Svt[Info]: SVT[build]:"

### ISSUE THREAD

**Issue by gitoss** [gianni-rosato/svt-av1-psy#71]
**Is your feature request related to a problem? Please describe.**
Considering the big speed differences with different compilers it would be nice to have the information if LLVM was used and which LLVM version for Visual Studio binaries.

**Describe the solution you'd like**

```
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]: ...
Svt[info]: SVT [build]  :       Visual Studio 2022 64 bit, Clang 19.1.0
Svt[info]: ...
Svt[info]: -------------------------------------------
```

**Describe alternatives you've considered**
I've considered posting this suggestion to the official SVT-AV1 repo, but the -PSY people seem to be very responsive :-)

**Additional context**
Current output of SVT-AV1-PSY with VC is like this

```
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:
Svt[info]: SVT [build]  :       Visual Studio 2022 64 bit
Svt[info]: LIB Build date:
Svt[info]: -------------------------------------------
```

Current output of SVT-AV1 with MSYS2 is like this
```
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:
Svt[info]: SVT [build]  :       Clang 18.1.8     64 bit
Svt[info]: LIB Build date:
Svt[info]: -------------------------------------------

```

**Comment by gianni-rosato** [comment]
Hey, thanks for the feature request!

We're happy to look into implementing this - before we put any work forward, could you make a feature request on mainline first? This may be something they are interested in implementing, which would save us some work.

If they aren't responsive, we will give this a closer look.
