### ISSUE TITLE
[ENHANCEMENT] Change dockerfile to svt-av1-psy

### ISSUE THREAD

**Issue by Uranite** [gianni-rosato/svt-av1-psy#72]
**Is your feature request related to a problem? Please describe.**
Dockerfile is currently for svt-av1

**Describe the solution you'd like**
Modify it so that it builds svt-av1-psy

**Describe alternatives you've considered**
None

**Additional context**
Someone in AV1 for dummies discord asked, "how can i run svt-av1-psy as a docker/"

**Comment by gianni-rosato** [comment]
1c9221c58bbb7a9384c3dc9a5be06fcf0753ce36
