### ISSUE TITLE
[ENHANCEMENT] auto-set --lp threads by max memory usage esp. for image encoding

### ISSUE THREAD

**Issue by gitoss** [gianni-rosato/svt-av1-psy#75]
**Is your feature request related to a problem? Please describe.**
The official SVT-AV1 is focussed on video encoding and thus, high resolution image encoding even using the current PSY branch has very high memory usage. 

While AOM happily slaves away, SVT crashes with 'out of memory' with high(er) thread number or slows down considerably with low(er)/1 threads. 
```
SvtMalloc[fatal]: allocate memory failed, at C:/mabs/build/svt-av1-psy-git/Source/Lib/Codec/pic_buffer_desc.c:98
[libsvtav1 @ 000000000051b2c0] Error initializing encoder: insufficient resources (0x80001000)

``` 

This is unfortunate, because --tune 4 is excellent in quality & speed, and works without seams in the image because SVT very good at threading w/o tiles.

**Describe the solution you'd like**
Esp. for still image encoding (maybe even useful for video encoding) SVT could have an option like --max-memory that calculates --lp according to the source image/video size.

**Describe alternatives you've considered**
I've considered (again) posting the request to the official repo, but they are clearly focussed on '4k and below' video encoding - and the PSY fork has come up with the already excellent --tune 4.

```
Svt[warn]: Instance 1: 8K and higher resolution support is currently a work-in-progress project, and is only available for demos, experimentation, and further development uses and should not be used for benchmarking until fully implemented.

Svt[warn]: Instance 1: 8K and higher resolution support below M8 isn't officially supported. 64 GB of available memory are recommended.
```

I've constrainted encoder memory usage with procgov and written a script that lowers the thread count until the encoder doesn't crash with oom, but that's rather ugly. 

In another script, I've tried to very roughtly predict the max threads without oom factoring in the free physical memory and image size - but I have no clue about the actual / precise memory logic of the encoder, thus this feature request.

**Additional context**
The SVT limitation "Source Height must be less than or equal to 8704" still wouldn't make it unlimited for high resolution sources, esp. in comparison to modern codecs that were actually designed for image encoding.

I'm using a Zen4 laptop with fixed memory, so no can do upgrading it. I've compiled m-ab-s ffmpeg & libavif with -PSY to use --tune 4, if anyone is interested in the (Zen4) binaries w/o compiling it again I could provide them.

**Comment by gianni-rosato** [comment]
I don't believe we should be making resource consumption decisions on behalf of our users, I think that should be left up to those using the encoder. Making these decisions would mean that performance would be even more inconsistent across different hardware configurations than it already is, and on top of that, our performance would begin to differ significantly from mainline's which would cause confusion. If you want to open this on the mainline repo, I think that is a better place for it.
