### ISSUE TITLE
[ENHANCEMENT] Stop relying on arbitary code files in `/thirdparty` and use libiaries instead

### ISSUE THREAD

**Issue by solomoncyj** [gianni-rosato/svt-av1-psy#76]
from https://bugzilla.redhat.com/show_bug.cgi?id=2316282
Breakdown of the `third_party` stuff:
- `aom/inc/aom`: Used only in tests. Should be available in Fedora through `aom` [2]. Delete if running the tests proves too hard, otherwise indicate in the SourceLicense breakdown or comments.
- `aom_dsp`: Same as above, but upstream does not seem to expose it.
- `cpuinfo`: Available in fedora build supports linking to it. Please delete it and use `-DUSE_EXTERNAL_CPUINFO=ON`.
- `fastfeat`: Dead project and there seems to be an alternative code-generated version [3]. For now though, just `Provides: bundled()` it and include it's license.
- `googletest`: Available in Fedora. Needs some patching to remove the `third_party/googletest` references and replace them with `find_package(GTest)`, `target_link_libraries(GTest::gtest GTest::gtest_main)` and a few other stuff. Alternatively open an issue and ask them to support linking against system `gtest` (or better have `FetchContent(FIND_PACKAGE_ARGS)` support).
- `safestringlib`: Available upstream project [4] but not packaged to Fedora. Please open an issue in either project to request supporting that.

In any case the license breakdown should indicate the `third_party` stuff, either inside the `License` field or `SourceLicense` field (for the case of `googletest` which is not packaged), and appropriate `Provides: bundled()` should be added.

[1]: https://src.fedoraproject.org/rpms/svt-av1/blob/rawhide/f/svt-av1.spec
[2]: https://src.fedoraproject.org/rpms/aom
[3]: https://github.com/edrosten/fast-C-src/issues/3
[4]: https://github.com/intel/safestringlib

**Comment by solomoncyj** [comment]
i am taking care of safestringlib atmbut beed help for 5

**Comment by quietvoid** [comment]
Why is this issue not at the upstream repo? The `third_party` code comes from there too.
