### ISSUE TITLE
[BUG] pkg config colficts with mainline svt-av1

### ISSUE THREAD

**Issue by solomoncyj** [gianni-rosato/svt-av1-psy#85]
**Overview**
The pkgconfig data generated conficts with mainline svt-av1. in packagmangers that have the ability to find the connect package by the pkg-config name, this could cause problmes. 

**Additional context / Relevant Files**
we should change the names to `SvtAv1PsyEnc`

**Comment by solomoncyj** [comment]
> Hi, can you describe your issue and proposed solution in more detail? From what I'm gathering, you'd like us to change the name of the .pc file generated from a build

yes, thanks

**Comment by gianni-rosato** [comment]
Hi, unfortunately we cannot fulfill this request as keeping our bulid process and distribution consistent with mainline's ensures full compatibility with anything supporting SVT-AV1. If we changed the pkg-config name, building SVT-AV1-PSY with tools like FFmpeg as a drop-in replacement for mainline SVT-AV1 would become impossible.
