### ISSUE TITLE
[BUG] --enable-tf 0 ignored

### ISSUE THREAD

**Issue by gitoss** [gianni-rosato/svt-av1-psy#87]
**Overview**
Using the last release 2.2.1-B, --enable-tf 1 and --enable-tf 0 both result in the information output "Svt[info]: SVT [config]: Temporal Filtering Strength: 1". I suspected this to be cosmetic, but a test encode results in the exact same file - i.e. disabling tf seems to be ignored - which is supposed to be useful for clean anime encoding.

**Branch**
In which branch does the issue appear to be occurring?
- [x] `master`
- [x] `testing`

**Reproduction**
SvtAv1EncApp.exe -i test.y4m --preset 4 --enable-tf 0 -o tf0.mp4
SvtAv1EncApp.exe -i test.y4m --preset 4 --enable-tf 1 -o tf1.mp4

**Expected behavior**
When usig --enable-tf 0, there should be no "Svt[info]: SVT [config]: Temporal Filtering Strength" and the resulting file shold (probably) be different from using the default --enable-tf 1

**Terminal Output**
`Svt[info]: SVT [config]: Temporal Filtering Strength:1
`

**Platform (please complete the following information):**
Windows 11 x64, usign the znver4 community build (VS Clang 17) plus my own build from the testing branch (VS Clang 19) both result in the same suspected bug.

**Version String (please complete the following information):**
```
SVT-AV1-PSY v2.2.1-B (release)
PSY Release: B

```

**Comment by gianni-rosato** [comment]
Hi, thanks for the issue report! We'll look into this as soon as possible.

**Comment by BlueSwordM** [comment]
Does this happen with the initial 2.2.0 release and any of the later releases?

**Comment by gianni-rosato** [comment]
@BlueSwordM I think this has been broken since the introduction of tf-strength, and it is just hard to notice normally now that the default temporal filter is so much weaker.

This issue is resolved as of 3397d0673aaa155b133dfc83d9542ca31536324b

Thanks for your patience!

**Comment by shssoichiro** [comment]
As a general question, the advice in the past has been to run with `--enable-tf 0` since temporal filtering was buggy in SVT. Is it safe to leave it enabled since the introduction of tf-strength? (In aom-psy the recommendation was typically to leave it enabled with a low strength.)
