### ISSUE TITLE
[BUG]Decoder Usage is empty，can you give this word?

### ISSUE THREAD

**Issue by silencexll** [gianni-rosato/svt-av1-psy#94]
**Overview**

**Branch**
In which branch does the issue appear to be occurring?
- [ ] `master`
- [ ] `testing`

**Reproduction**

**Expected behavior**

**Terminal Output**
If applicable, add terminal output to help explain your problem.

**Platform (please complete the following information):**
 - Operating System (preferably formatted as the output of `uname -mnoprs`)
 - Clang/GCC Version (`clang --version` or GCC equivalent)
 - Build Command (`./build.sh [args]` that you used to build the problematic binary)

**Version String (please complete the following information):**
- Run `SvtAv1EncApp --version` and copy the result: `here`

**Additional context / Relevant Files**
Add any other context about the problem here, or files that must be attached for reproduction of the issue, visual inspection, etc.

**Comment by gianni-rosato** [comment]
The SVT-AV1 decoder project is no longer part of mainline SVT-AV1.

1df03373cf05dcbf29f27048364bdbff405c498d
