### ISSUE TITLE
[BUG]The encoding is poor 

### ISSUE THREAD

**Issue by silencexll** [gianni-rosato/svt-av1-psy#98]
**Overview**
Use the SvtAv1EncApp.exe from the build and encode it with the RaceHorses_832x480_30.yuv video from ClassC. Using the encoding command given in your example : SvtAv1EncApp -i RaceHorses_832x480_30.yuv -w 832 -h 480 --fps 30 --crf 30 --preset 12 -b output.ivf. The resulting IVF file cannot be opened with the original video content at all, it is full of mosaics.

**Branch**
In which branch does the issue appear to be occurring?
- [ ] `master`
The project I pulled from gothub using the build steps

**Reproduction**
1. open cmd
2. input the command: SvtAv1EncApp -i RaceHorses_832x480_30.yuv -w 832 -h 480 --fps 30 --crf 30 --preset 12 -b output.ivf
3. get a file named output.ivf
4. open output.ivf

**Expected behavior**
According the build steps, I get a SvtAv1EncApp.exe, I input the encode command you give
![image](https://github.com/user-attachments/assets/f4be42e3-b060-48d2-9076-5a9e4f863fc3)
I open the output.ivf(about 38MB) with VLC media player，it is full of mosaics，like this.
![image](https://github.com/user-attachments/assets/0c56d41c-442a-4d2d-b959-140b23be3d2f)
But original RaceHorses_832x480_30.yuv is like this
![image](https://github.com/user-attachments/assets/1bbb102b-3010-46b0-b73b-17bef3e30e77)
**Terminal Output**
cmd input: SvtAv1EncApp -i RaceHorses_832x480_30.yuv -w 832 -h 480 --fps 30 --crf 30 --preset 12 -b output.ivf
cmd output: 
![image](https://github.com/user-attachments/assets/50478441-e4ca-45d3-8923-55c6e99d1953)
**Platform (please complete the following information):**
 - Operating System : Windows11
 - Clang/GCC Version : gcc.exe (Rev1, Built by MSYS2 project) 14.2.0
 - Build Command (`./build.sh [args]` that you used to build the problematic binary)

**Version String (please complete the following information):**
- Run `SvtAv1EncApp --version` and copy the result: SVT-AV1-PSY v2.3.0-1-g916cabd5 (release)

**Additional context / Relevant Files**
Add any other context about the problem here, or files that must be attached for reproduction of the issue, visual inspection, etc.

**Comment by gianni-rosato** [comment]
Hi,

Thanks for the issue report. We'll look at this as soon as possible.

Are you able to provide us with the link you used to acquire the source video, or an archive containing the source video material?

**Comment by juliobbv-p** [comment]
@silencexll, make sure to pass in the correct `--input-depth`, because it's not included with the raw YUV. Knowing the kind of clip this is, it should be 8 bits, so pass in `--input-depth 8`.

**Comment by silencexll** [comment]
Thank you very much! This problem has been sovled because of your suggestion.
